name: security_key_generator
description: "A generator for create and read key to or from a FlashDisk, by detecting desktop usb serial port"
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ^3.5.3
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    page_transition: ^2.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true
